version: '3.1'

services:

  adminer:
    container_name: adminer_bot
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    container_name: mysql_db
    image: mysql:5.6
    restart: always
    command: --init-file /db/db.sql
    hostname: 127.0.0.2
    volumes:
      - ./db/db.sql:/db/db.sql
    env_file:
      - .env
    ports:
      - 3307:3306

  tg_bot:
    container_name: my_bot
    build:
      context: .
    command:
      - python3
      - app.py
    restart: always
    env_file:
      - ".env"